service: aws-email-server

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
        - events:*
      Resource: "*"

functions:
  send-email:
    handler: send-email.handler
    description: Generic email sender
    events:
      - http:
          path: api/send-email
          method: post
          integration: lambda
          cors: true

